### ISSUE TITLE
Update structure for how SPICE is integrated

### ISSUE THREAD

**Issue by nfahlgren** [danforthcenter/plantcv-hyperspectral#36]
@CJRobey it looks like there is an issue with #35 because of the new `QPP` module in SPICE. In SPICE itself `from SPICE import *` works because `QPP` is present relative to SPICE. Within the plantcv namespace `QPP` doesn't exist in the same context. I tried a few different things to get around this, my goal was to keep SPICE functionality as a stand-alone package as unchanged as possible while also making it easy to integrate within PlantCV as we have done. Here's my proposed solution:

1. Reorganize the main SPICE_py repository a little to create a SPICE namespace. The new namespace would work in standalone SPICE just like before. Within plantcv-hyperspectral the relative imports should work within the plantcv namespace. I opened a pull request at `GatorSense/SPICE_py` with these changes.
2. If 1 works, we need to update the subtree and then update `plantcv-hyperspectral/plantcv/hyperspectral/__init__.py`. The import `from plantcv.hyperspectral import SPICE` needs to be updated to `from plantcv.hyperspectral.SPICE import SPICE`

How does this sound?

**Comment by CJRobey** [comment]
Hey Noah, I apologize on how long this took, but that sounds great. I just merged your changes into the SPICE_py repo. Would you like me to do the subtree update and __init__.py updates?

**Comment by nfahlgren** [comment]
@CJRobey no worries, sounds great!
